### ISSUE TITLE
Please keep compatibility with Qt4

### ISSUE THREAD

**Issue by barracuda156** [kylelutz/chemkit#42]
Somewhat recent commit https://github.com/kylelutz/chemkit/commit/0afc7883c858ab9b20dd12bf8adbf88268ab5583 has replaced Qt4 with Qt5. If possible, please maintain the former for the sake of better compatibility (not all systems have Qt5).

**Comment by quizzmaster** [comment]
The mentioned commit is almost 9 years old. Since the support of Qt4 ended in 2015 and most Linux distributions don't contain Qt4 anymore you might want to upgrade your systems. The support of Qt5 ended in May 2023 so we will soon change to Qt6.

If you really need Qt4 you can revert the changes of this commit on your local machine.

**Comment by barracuda156** [comment]
Got it, thank you for replying. Yes, I noticed the age of the commit, but there were not many commits during past several years.
